oriental_position_controller:
  type: position_controllers/JointPositionController
  joint: ball_screw_joint

oriental_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1